services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        COMPOSER_FLAGS: ""  # ← Пустая строка = устанавливаем ВСЕ зависимости (включая dev)
    volumes:
      - ./backend:/var/www/html
      - ./.env:/var/www/html/.env

  websockets:
    volumes:
      - ./backend:/var/www/html
    ports:
      - "6001:6001"

  vue:
    volumes:
      - ./frontend:/app
      - vue_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vue
      - websockets

  mysql:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

volumes:
  vue_node_modules:

networks:
  app_network:
    driver: bridge