services:
  vue:
    # В dev запускаем vite dev-server, пробрасываем порт
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

  nginx:
    # В dev nginx проксирует на vite (frontend:5173) и на php-fpm (laravel)
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vue
      - laravel
